import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const monserrat = localFont({
  src: "./fonts/MontserratVF.woff",
  variable: "--font-montserrat",
  weight: "100 900",
});

const monserratItalic = localFont({
  src: "./fonts/MontserratItalicVF.woff",
  variable: "--font-montserrat-italic",
  weight: "100 900",
});

const righteous = localFont({
  src: "./fonts/RighteousRegularVF.woff",
  variable: "--font-righteous",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${monserrat.variable} antialiased w-full h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
