import Image from "next/image";
import "./globals.css";

export const metadata = {
  title: "e-mifda",
  description: "Generated by create next app",
  Icon: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        style={{
          height: "100vh",
          width: "100vw",
          overflow: "hidden",
        }}
      >
        {children}
      </body>
    </html>
  );
}
